# Generated by Django 6.1.1 on 2026-09-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('SALARY_DEDUCTION', 'Salary Deduction'), ('OTHER', 'Other')], default='CASH', help_text='How the payment was made', max_length=20),
        ),
    ]
