# Generated by Django 6.1 on 2026-08-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('factor', models.CharField(choices=[('INCOME', 'Income'), ('EMPLOYMENT', 'Employment Stability'), ('OBLIGATIONS', 'Existing Obligations'), ('REPAYMENT_HISTORY', 'Repayment History')], max_length=50, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight as percentage (e.g., 30.00 for 30%)', max_digits=5)),
                ('thresholds', models.JSONField(default=list, help_text='List of threshold objects: [{"min": 0, "max": 5000, "score": 20}, ...]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eligibility rule',
                'verbose_name_plural': 'eligibility rules',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breakdown', models.JSONField(default=dict, help_text='Score breakdown by factor')),
                ('recommendation', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('REVIEW', 'Review'), ('NOT_ELIGIBLE', 'Not Eligible')], max_length=20)),
                ('reasons', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'eligibility score',
                'verbose_name_plural': 'eligibility scores',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
