# Generated by Django 6.1 on 2026-08-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('nrc_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('PART_TIME', 'Part Time'), ('RETIRED', 'Retired')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('membership_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'ordering': ['-created_at'],
            },
        ),
    ]
