# Generated by Django 6.1.1 on 2026-09-20 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='member',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='income_verified',
            field=models.BooleanField(default=False, help_text='Admin has verified the declared income'),
        ),
        migrations.AddField(
            model_name='member',
            name='income_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='verified_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Income verified by administrator (falls back to declared)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='PENDING', help_text='New signups start as PENDING until admin approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, help_text='Declared monthly income', max_digits=12),
        ),
    ]
