# Generated by Django 6.1 on 2026-08-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaulterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_overdue', models.IntegerField()),
                ('classification', models.CharField(choices=[('CURRENT', 'Current'), ('AT_RISK', 'At Risk'), ('DEFAULTER', 'Defaulter'), ('SEVERE_DEFAULTER', 'Severe Defaulter')], max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'defaulter status',
                'verbose_name_plural': 'defaulter statuses',
                'ordering': ['-days_overdue'],
            },
        ),
    ]
