# Generated by Django 6.1 on 2026-08-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defaulters', '0003_initial'),
        ('repayments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulterstatus',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaulter_statuses', to='repayments.repaymentschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='defaulterstatus',
            unique_together={('member', 'loan', 'schedule')},
        ),
    ]
